apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-headlamp
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Optional headers; you can remove these if you donâ€™t want them on Headlamp
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   add_header Content-Security-Policy "default-src 'self'; connect-src 'self' https: wss:; img-src 'self' data: blob: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; frame-ancestors 'self'; base-uri 'self'" always;
    #   add_header Set-Cookie "umami-tracking=1; Path=/; Secure; HttpOnly" always;
spec:
  ingressClassName: public
  rules:
    - host: headlamp.publio.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-headlamp
                port:
                  number: 80
  tls:
    - hosts:
        - headlamp.publio.online
      secretName: headlamp-tls
