apiVersion: v1
kind: Service
metadata:
  name: velo
  namespace: velo
  labels:
    app: velo
spec:
  selector:
    app: velo 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8501
  type: ClusterIP

