apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimat-ingress
  namespace: heimat
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: public
  rules:
  - host: heimat.publio.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: heimat
            port:
              number: 80
  tls:
  - hosts:
    - heimat.publio.online
    secretName: heimat-tls
