image:
  repository: linuxserver/jellyfin
  tag: 10.10.6
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "911"
  - name: PGID
    value: "911"
  - name: UMASK
    value: "002"
  - name: JELLYFIN_TRICKPLAYENABLED
    value: "false"

ingress:
  enabled: false

podSecurityContext:
  fsGroup: 65534

service:
  type: ClusterIP
  port: 8096

persistence:
  config:
    enabled: true
    existingClaim: jellyfin-config
    size: 5Gi

  cache:
    enabled: true
    storageClass: microk8s-hostpath
    accessMode: ReadWriteOnce
    size: 2Gi

  media:
    enabled: true
    mountPath: /media
    existingClaim: jellyfin-media

  transcode:
    enabled: true
    existingClaim: jellyfin-transcode

