apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adsb-radarscope-ing
  namespace: radar
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cf
spec:
  ingressClassName: public
  rules:
  - host: scope.peluan.com         # pick what you like :)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adsb-radarscope
            port:
              number: 80
  tls:
  - hosts:
    - scope.peluan.com
    secretName: scope-tls
